[package]
name = "aoc_2024"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
aoc-rs = "0.1.1"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
regex = "1.11.1"
